export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
