export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const GET_RESTAURANTS_REQUEST = 'GET_RESTAURANTS_REQUEST';
export const CREATE_RESTAURANT_REQUEST = 'CREATE_RESTAURANT_REQUEST';
export const UPDATE_RESTAURANT_REQUEST = 'UPDATE_RESTAURANT_REQUEST';
export const DELETE_RESTAURANT_REQUEST = 'DELETE_RESTAURANT_REQUEST';
export const SET_RESTAURANT = 'SET_RESTAURANT';

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
